from generation.llm import get_chat_model
from generation.prompt import BASELINE_PROMPT
from generation.formatter import format_documents
from langchain_core.output_parsers import StrOutputParser

def generate_answer(question, retrieved_docs):
    """
    Answers a user question using the baseline RAG pipeline.

    Args:
        question (str): User's question.
        retrieved_docs: Retrieved documents for input question.

    Returns:
        str: Answer generated by the model.
    """

    formatted_context = format_documents(retrieved_docs)

    model = get_chat_model()

    chain = BASELINE_PROMPT | model | StrOutputParser()

    return chain.invoke(
        {
            "context": formatted_context,
            "question": question,
        }
    )